name = "plateo"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-04-12"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "plateo-db"
database_id = "f5c97ceb-f8e3-4dc9-908d-e6bda5ab7f11"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "plateo-uploads"