# fly.toml app configuration file generated for plateo-bitter-shape-4204 on 2024-03-03T09:55:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'plateo-bitter-shape-4204'
primary_region = 'arn'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
