import type { Metadata } from "next";
import { Inter, Quicksand } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], display: "swap" });
const quicksand = Quicksand({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <style>{`
          h1,
          h2,
          h3,
          h4 {
            font-family: ${quicksand.style.fontFamily};
          }
        `}</style>
      </head>
      <body className={`${quicksand.className} min-h-screen`}>{children}</body>
    </html>
  );
}
